# Generated by Django 6.0.2 on 2026-02-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('quero_ler', 'Quero Ler'), ('lendo', 'Lendo'), ('lido', 'Lido')], default='quero_ler', max_length=20)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
